export const FETCH_PRODUCT_LIST_START = 'FETCH_PRODUCT_LIST_START';
export const FETCH_PRODUCT_LIST_SUCCESS = 'FETCH_PRODUCT_LIST_SUCCESS';
export const FETCH_PRODUCT_LIST_FAIL = 'FETCH_PRODUCT_LIST_FAIL';

export const FETCH_PRODUCT_DETAILS_START = 'FETCH_PRODUCT_DETAILS_START';
export const FETCH_PRODUCT_DETAILS_SUCCESS = 'FETCH_PRODUCT_DETAILS_SUCCESS';
export const FETCH_PRODUCT_DETAILS_FAIL = 'FETCH_PRODUCT_DETAILS_FAIL';

export const TOGGLE_CART_HIDDEN = 'TOGGLE_CART_HIDDEN';

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const CLEAR_PRODUCT_FROM_CART = 'CLEAR_PRODUCT_FROM_CART';
export const CLEAR_ALL_PRODUCT_FROM_CART = 'CLEAR_ALL_PRODUCT_FROM_CART';
