export const USER_AUTH_START = 'USER_AUTH_START';
export const USER_AUTH_FAIL = 'USER_AUTH_FAIL';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';

export const USER_PROFILE_FETCH_START = 'USER_PROFILE_FETCH_START';
export const USER_PROFILE_FETCH_FAIL = 'USER_PROFILE_FETCH_FAIL';
export const USER_PROFILE_FETCH_SUCCESS = 'USER_PROFILE_FETCH_SUCCESS';
export const USER_PROFILE_FETCHED_CLEAR = 'USER_PROFILE_FETCHED_CLEAR';

export const USER_PROFILE_UPDATE_START = 'USER_PROFILE_UPDATE_START';
export const USER_PROFILE_UPDATE_FAIL = 'USER_PROFILE_UPDATE_FAIL';
export const USER_PROFILE_UPDATE_SUCCESS = 'USER_PROFILE_UPDATE_SUCCESS';
export const USER_PROFILE_UPDATE_CLEAR = 'USER_PROFILE_UPDATE_CLEAR';

export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_RESET_ERROR = 'USER_RESET_ERROR';

export const PRODUCT_LIST_FETCH_START = 'PRODUCT_LIST_FETCH_START';
export const PRODUCT_LIST_FETCH_FAIL = 'PRODUCT_LIST_FETCH_FAIL';
export const PRODUCT_LIST_FETCH_SUCCESS = 'PRODUCT_LIST_FETCH_SUCCESS';

export const PRODUCT_SELECTED_FETCH_START = 'PRODUCT_SELECTED_FETCH_START';
export const PRODUCT_SELECTED_FETCH_FAIL = 'PRODUCT_SELECTED_FETCH_FAIL';
export const PRODUCT_SELECTED_FETCH_SUCCESS = 'PRODUCT_SELECTED_FETCH_SUCCESS';

export const CART_DROPDOWN_TOGGLE_HIDDEN = 'CART_DROPDOWN_TOGGLE_HIDDEN';
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';

export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_MODIFY_QUANTITY_FOR_ITEM = 'CART_MODIFY_QUANTITY_FOR_ITEM';
export const CART_CLEAR_ITEM = 'CART_CLEAR_ITEM';
export const CART_RESET = 'CART_RESET';

export const CART_ITEMS_DETAIL_FETCH_START = 'CART_ITEMS_DETAIL_FETCH_START';
export const CART_ITEMS_DETAIL_FETCH_FAIL = 'CART_ITEMS_DETAIL_FETCH_FAIL';
export const CART_ITEMS_DETAIL_FETCH_SUCCESS = 'CART_ITEMS_DETAIL_FETCH_SUCCESS';

export const ORDER_CREATE_START = 'ORDER_CREATE_START';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';

export const ORDERS_LIST_FETCH_START = 'ORDERS_LIST_FETCH_START';
export const ORDERS_LIST_FETCH_FAIL = 'ORDERS_LIST_FETCH_FAIL';
export const ORDERS_LIST_FETCH_SUCCESS = 'ORDERS_LIST_FETCH_SUCCESS';
export const ORDERS_LIST_FETCH_RESET = 'ORDERS_LIST_FETCH_RESET';

export const ORDER_DETAILS_FETCH_START = 'ORDER_DETAILS_FETCH_START';
export const ORDER_DETAILS_FETCH_FAIL = 'ORDER_DETAILS_FETCH_FAIL';
export const ORDER_DETAILS_FETCH_SUCCESS = 'ORDER_DETAILS_FETCH_SUCCESS';
export const ORDER_DETAILS_FETCH_RESET = 'ORDER_DETAILS_FETCH_RESET';

export const ORDER_PAY_START = 'ORDER_PAY_START';
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL';
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET';
