export const PRODUCT_LIST_FETCH_START = 'PRODUCT_LIST_FETCH_START';
export const PRODUCT_LIST_FETCH_SUCCESS = 'PRODUCT_LIST_FETCH_SUCCESS';
export const PRODUCT_LIST_FETCH_FAIL = 'PRODUCT_LIST_FETCH_FAIL';

export const PRODUCT_SELECTED_FETCH_START = 'PRODUCT_SELECTED_FETCH_START';
export const PRODUCT_SELECTED_FETCH_SUCCESS = 'PRODUCT_SELECTED_FETCH_SUCCESS';
export const PRODUCT_SELECTED_FETCH_FAIL = 'PRODUCT_SELECTED_FETCH_FAIL';

export const CART_TOGGLE_HIDDEN = 'CART_TOGGLE_HIDDEN';

export const CART_ADD_PRODUCT = 'CART_ADD_PRODUCT';
export const CART_DECREASE_PRODUCT = 'CART_DECREASE_PRODUCT';
export const CART_CLEAR_PRODUCT = 'CART_CLEAR_PRODUCT';
